apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkding
resources:
  - ../../base/linkding/
  - cloudflare-secret.yaml
    #- cloudflare.yaml
  - linkding-container-env-secret.yaml
